### ISSUE TITLE
Using a linter to format HTML markup

### ISSUE THREAD

**Issue by zannain** [sandeepdhillo/prj-rev-bwfs-dasmoto#1]
I recommend installing a linter for any language that you are working in. Linters serve to catch possible errors such as forgetting to close an element tag and they also serve to ensure proper indentation. This will ensure the code you are writing is properly formatted, easy to read and following standards. 

_Before Linter_
![image](https://user-images.githubusercontent.com/24375741/40270905-4c64c6e4-5b63-11e8-8544-631e44b61c3c.png)

_After Linter_
![image](https://user-images.githubusercontent.com/24375741/40270914-7127f91a-5b63-11e8-84ee-de5e1f7809c6.png)

You can see in the screenshot that there is a[ `<span>` tag](https://github.com/sandeepdhillo/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's%20Arts%20%26%20Crafts/index.html#L24) that isn't properly closed

**Comment by sandeepdhillo** [comment]
Ok thanks
