### ISSUE TITLE
Functional comments

### ISSUE THREAD

**Issue by zannain** [sandeepdhillo/prj-rev-bwfs-dasmoto#2]
Good work on adding comments! I recommend being descriptive with your comments. When you start developing websites with more than one page `<!-- Main Headings -->` and `<!--Sub Headings-->` is fairly vague. Describing what is being marked up will help you find sections of a webpage later. Extending this same pattern of comments to the CSS stylesheet will help you locate style if you need to change them after initially creating the webpage.

**Comment by sandeepdhillo** [comment]
Right Thanks
