### ISSUE TITLE
Using ID selectors for unique styles

### ISSUE THREAD

**Issue by zannain** [sandeepdhillo/prj-rev-bwfs-dasmoto#4]
If a style is unique such as the [`background color`](https://github.com/sandeepdhillo/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's%20Arts%20%26%20Crafts/resources/index.css#L17), using an ID selector is more appropriate. This ensures that the styles won't be overwritten as ID selectors are more specific than element and class selectors.

**Comment by sandeepdhillo** [comment]
Ok
