### ISSUE TITLE
Summary: Meets expectations

### ISSUE THREAD

**Issue by zannain** [sandeepdhillo/prj-rev-bwfs-dasmoto#5]
Awesome work on this mockup! Props for making the webpage accessible by using the `alt` attribute in the `<img>` tags and for adding comments to the HTML markup. I would recommend extending the latter to the stylesheet well to help you organize the webpage. Going forward I recommend learning about Flexbox and CSS grid's as they are key players when it comes to responsive design. I've listed a few resources below to get you going. **Keep up the excellent work Sandeep!**

**Resources**
[Responsive Design](https://www.codecademy.com/learn/learn-responsive-design)
[CSS Grid Course](https://www.codecademy.com/courses/learn-css-grid/lessons/css-grid-i/exercises/grid-intro?course_redirect=learn-css)
[Flexbox course](https://flexbox.io/)
[CSS Grids](https://cssgrid.io/)
[CSSGridGarden game](https://cssgridgarden.com/)
[FlexboxFroggy](https://flexboxfroggy.com/)

**Comment by sandeepdhillo** [comment]
Thank you Zannain for you quick and elaborate review. I'll keep in mind all the things that you have told me, next time .
